### ISSUE TITLE
NullPointerException in launchPurchaseFlow

### ISSUE THREAD

**Issue by thomasuster** [openfl/extension-iap#28]
Hey

This is a report we got from Flurry. 

@bryanchacosky 

386 is this line.

```
Bundle buyIntentBundle = mService.getBuyIntent(3, mContext.getPackageName(), sku, itemType, extraData);
```

So either mService, mContext is null.

Full Stack Trace:
java.lang.NullPointerException
org.haxe.extension.iap.util.IabHelper.launchPurchaseFlow(IabHelper.java:386)
org.haxe.extension.iap.util.IabHelper.launchPurchaseFlow(IabHelper.java:338)
org.haxe.extension.iap.InAppPurchase$1.run(InAppPurchase.java:39)
android.os.Handler.handleCallback(Handler.java:808)
android.os.Handler.dispatchMessage(Handler.java:103)
android.os.Looper.loop(Looper.java:193)
android.app.ActivityThread.main(ActivityThread.java:5332)
java.lang.reflect.Method.invokeNative(Native Method)
java.lang.reflect.Method.invoke(Method.java:515)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
dalvik.system.NativeStart.main(Native Method)

**Comment by bryanchacosky** [comment]
So there's two potential null properties: `mContext` and `mService`.

`mContext` cannot be null. It's assigned in the constructor from a non-nullable getter, and is only unassigned if `dispose()` is called. But if `dispose()` were called, `launchPurchaseFlow` would have thrown an exception on line 371.

`mService` has only scenario where it can be null: if the billing services were at one point connected, `mSetupDone` has been set to true (otherwise you would see the exception at line 372), and at some point the services were disconnected before the purchase call was made. Looking at the documentation, this seems only happen if there is a crash in the service itself.

Do you have multiple reports of it? I'm suspect that this would be a common issue since the IabHelper is written by Google, but a new check/throw could be added if you're concerned about it or seeing more instances.

**Comment by thomasuster** [comment]
One report so far, but we don't have that many users and it's only been a day.

Perhaps onServiceDisconnected is a case we should handle better. Looking here...
http://stackoverflow.com/questions/971824/when-does-serviceconnection-onservicedisconnected-get-called

In the comments they say not to do anything, as it might re-connect. Perhaps we're nulling mService out for no good reason?

**Comment by bryanchacosky** [comment]
Nulling out `mService` should be the correct response to service disconnect. I think what the poster is saying is that the connection itself has been disconnect (meaning we shouldn't use it so null is appropriate) but the connection service is still bound, so the connection will be re-established and `mService` will be set again.

I don't recommend any action, but, if anything, I would say an assertion against `mService` in the beginning of the purchase method, like lines 371 and 372 do for dispose() and setup done.

**Comment by thomasuster** [comment]
```
if(mService == null)
  cancelPurchase();
```
That kind of thing?

**Comment by bryanchacosky** [comment]
I would implement it similar to the `checkNotDisposed()` method:

```java
private void checkNotConnected() {
    if (mService == null) throw new IllegalStateException("...");
}
```

and then the call from `InAppPurchase.java` should be try/catching it (although it looks like it should be try/catching it anyways).

**Comment by bryanchacosky** [comment]
I've received a few reports of this in production. I think the assumption in an earlier post is correct; this is a timing issue where the purchase service is disconnect (for whatever reason beyond our control) and has not been reconnected.

On second thought, it didn't seem wise to change `IabHelper.java` so we can support future versions. I'm preparing a commit with a change in `InAppPurchase.java` to wrap the `launchPurchaseFlow()` call in a try/catch and respond to the listener appropriately. The try/catch in `IabHelper.launchPurchaseFlow()` doesn't account for `NullPointerException` so we can receive it outside.

**Comment by thomasuster** [comment]
Cool, let me know how it goes please!
